import {setEntitlement,setCharge} from "./_payment-store.js";
const BOT_TOKEN=process.env.TELEGRAM_BOT_TOKEN;
const SUPPORT_CHAT_ID=process.env.TELEGRAM_SUPPORT_CHAT_ID||"";
const COCKPIT_URL=process.env.COCKPIT_URL||(process.env.VERCEL_URL?`https://${process.env.VERCEL_URL}`:"https://futurebusinesscockpit.de");
const PRICES={employee:50,team:150};
function esc(v=""){return String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
async function tg(method,payload={}){if(!BOT_TOKEN)throw new Error("TELEGRAM_BOT_TOKEN is missing");const r=await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!d.ok)throw new Error(`${method}: ${d.description||"Telegram API error"}`);return d.result}
function keyboard(){return{inline_keyboard:[[{text:"📊 Cockpit öffnen",web_app:{url:COCKPIT_URL}}],[{text:"💬 Feedback",callback_data:"support:feedback"},{text:"❓ Frage",callback_data:"support:question"}],[{text:"🐞 Fehler melden",callback_data:"support:error"}]]}}
const prompts={feedback:"💬 Feedback\nSchreib uns bitte dein Feedback. / Напишите ваш отзыв.",question:"❓ Frage / Вопрос\nSchreib bitte deine Frage. / Напишите ваш вопрос.",error:"🐞 Fehler / Ошибка\nBeschreibe bitte kurz, was nicht funktioniert. / Коротко опишите, что не работает."};
function meta(message){const u=message.from||{},cid=message.chat.id,user=u.username?`@${u.username}`:"—",name=[u.first_name,u.last_name].filter(Boolean).join(" ")||"—";return `<b>Nachricht / Сообщение</b>\nName: ${esc(name)}\nUsername: ${esc(user)}\nUser ID: <code>${cid}</code>\n[#uid:${cid}]`}
function uidFrom(s){const m=String(s||"").match(/\[#uid:(-?\d+)\]/);return m?m[1]:null}
function parsePayload(v){const m=String(v||'').match(/^fbc\|(employee|team)\|([a-f0-9]{24})\|(\d+)$/);return m?{scope:m[1],calcId:m[2],stars:Number(m[3])}:null}
async function forward(message){const cid=message.chat.id;if(!SUPPORT_CHAT_ID){await tg("sendMessage",{chat_id:cid,text:"Support wird gerade eingerichtet. / Поддержка сейчас настраивается."});return}const m=meta(message);if(message.photo?.length){await tg("sendPhoto",{chat_id:SUPPORT_CHAT_ID,photo:message.photo.at(-1).file_id,caption:`${m}\n\n${esc(message.caption||"(Screenshot / Foto)")}`,parse_mode:"HTML"})}else if(message.document){await tg("sendDocument",{chat_id:SUPPORT_CHAT_ID,document:message.document.file_id,caption:`${m}\n\n${esc(message.caption||message.document.file_name||"Dokument")}`,parse_mode:"HTML"})}else{await tg("sendMessage",{chat_id:SUPPORT_CHAT_ID,text:`${m}\n\n${esc(message.text||message.caption||"(ohne Text)")}`,parse_mode:"HTML"})}await tg("sendMessage",{chat_id:cid,text:"Danke. Deine Nachricht wurde weitergeleitet. / Спасибо. Сообщение передано."})}
export default async function handler(req,res){if(req.method!=="POST")return res.status(405).send("Method Not Allowed");try{const u=req.body||{};
  if(u.pre_checkout_query){const q=u.pre_checkout_query,p=parsePayload(q.invoice_payload),valid=p&&PRICES[p.scope]===p.stars&&q.currency==='XTR'&&Number(q.total_amount)===p.stars;await tg("answerPreCheckoutQuery",{pre_checkout_query_id:q.id,ok:!!valid,...(!valid?{error_message:"Diese Zahlung konnte nicht validiert werden. Bitte öffne die Auswertung erneut."}:{})});return res.status(200).send("ok")}
  const m=u.message;if(!m){if(u.callback_query){const cb=u.callback_query;await tg("answerCallbackQuery",{callback_query_id:cb.id});const type=String(cb.data||"").split(":")[1];if(prompts[type])await tg("sendMessage",{chat_id:cb.message.chat.id,text:prompts[type],reply_markup:{force_reply:true,selective:true}})}return res.status(200).send("ok")}
  if(m.successful_payment){const sp=m.successful_payment,p=parsePayload(sp.invoice_payload);if(!p||sp.currency!=='XTR'||Number(sp.total_amount)!==p.stars||PRICES[p.scope]!==p.stars)throw new Error("Invalid successful_payment payload");const uid=m.from?.id||m.chat.id;const record={paid:true,uid,scope:p.scope,calcId:p.calcId,stars:p.stars,chargeId:sp.telegram_payment_charge_id,paidAt:new Date().toISOString()};await setEntitlement(uid,p.scope,p.calcId,record);await setCharge(sp.telegram_payment_charge_id,record);await tg("sendMessage",{chat_id:m.chat.id,text:`✅ Zahlung bestätigt: ${p.stars} ⭐\n${p.scope==='employee'?'Mitarbeiter-Auswertung':'Team-Auswertung'} ist für diesen Berechnungsstand freigeschaltet.\n\nÖffne das Cockpit wieder, falls die Freischaltung nicht sofort sichtbar ist.`,reply_markup:keyboard()});return res.status(200).send("ok")}
  if(String(m.chat.id)===String(SUPPORT_CHAT_ID)&&m.reply_to_message){const uid=uidFrom(m.reply_to_message.text||m.reply_to_message.caption);if(uid&&m.text){await tg("sendMessage",{chat_id:uid,text:`FUTURE Business Cockpit · Support\n\n${m.text}`});return res.status(200).send("ok")}}
  if(m.text?.startsWith("/start")){await tg("sendMessage",{chat_id:m.chat.id,text:"FUTURE Business Cockpit\n\nKalkulation für Selbständige und kleine Gewerbe · DE / RU",reply_markup:keyboard()});return res.status(200).send("ok")}
  if(m.text==="/myid"){await tg("sendMessage",{chat_id:m.chat.id,text:`Deine Chat-ID: ${m.chat.id}`});return res.status(200).send("ok")}
  if(m.text?.startsWith("/paysupport")){await tg("sendMessage",{chat_id:m.chat.id,text:"Zahlungsfragen / Вопросы по оплате\n\nBitte antworte auf diese Nachricht mit einer kurzen Beschreibung. Bei einer Zahlung nenne, wenn möglich, Datum und Anzahl der Stars.\n\nОтветьте на это сообщение и кратко опишите проблему. Если платёж уже был, укажите дату и количество Stars.",reply_markup:{force_reply:true}});return res.status(200).send("ok")}
  if(m.text?.startsWith("/terms")){await tg("sendMessage",{chat_id:m.chat.id,text:"FUTURE Business Cockpit · Zahlungsbedingungen (Beta)\n\nDie Stars-Zahlung ist einmalig und schaltet den aktuellen Berechnungsstand frei. Kein Abo. Bei Zahlungsproblemen: /paysupport. Vor dem öffentlichen Release werden die vollständigen Rechtstexte auf futurebusinesscockpit.de veröffentlicht."});return res.status(200).send("ok")}
  await forward(m);return res.status(200).send("ok")
}catch(e){console.error(e);return res.status(500).send("error")}}
